; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
monitor_speed = 9600
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
lib_deps = 
	artronshop/ArtronShop_BH1750@^1.0.0
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit INA3221 Library@^1.0.1
	jpb10/SolarCalculator@^2.0.2
	paulstoffregen/Time@^1.6.1
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.2.2
	arduino-libraries/ArduinoMqttClient@^0.1.8
	alecxcode/LX16A-bus@^1.1.0
	arduino-libraries/NTPClient@^3.2.1
	wollewald/MPU9250_WE@^1.2.17
	robtillaart/I2C_SOFTRESET@^0.1.1
	mathertel/RotaryEncoder@^1.6.0
