; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno_r4_wifi]
monitor_speed = 9600
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
lib_deps = 
	artronshop/ArtronShop_BH1750@^1.0.0
	adafruit/DHT sensor library@^1.4.7
	adafruit/Adafruit LSM303 Accel@^1.1.9
	adafruit/Adafruit INA3221 Library@^1.0.1
	adafruit/Adafruit LIS2MDL@^2.1.8
	jpb10/SolarCalculator@^2.0.2
	paulstoffregen/Time@^1.6.1
